
spring:
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/test_1
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.keyt.test_1.bean